FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8

COPY ./publisher.py /app/publisher.py
COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt

CMD ["uvicorn", "publisher:app", "--host", "0.0.0.0", "--port", "8000"]