version: '3.9'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  publisher:
    build: ./publisher
    depends_on:
      - redis
    ports:
      - "8000:8000"

  subscriber:
    build: ./subscriber
    depends_on:
      - redis