FROM python:3.8-slim

COPY ./subscriber.py /app/subscriber.py
COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt

CMD ["python", "/app/subscriber.py"]